name: Terraform Destroy

on:
  workflow_dispatch:  # Manual trigger only to avoid accidental deletion

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_VAR_environment: production  # Ensure correct environment
      TF_INPUT: false  # Prevent interactive prompts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::989557614958:role/TerraformGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=terraform-state-prod-1234567890" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"

      # - name: Select Terraform Workspace
      #   run: terraform workspace select production || terraform workspace new production

      - name: Plan Destroy (Preview)
        run: terraform plan -destroy -out=destroy.plan

      - name: Apply Destroy (Confirm)
        run: terraform apply -auto-approve destroy.plan

      - name: destroy
        run: terraform destroy -auto-approve
